trigger:
- main

pool:
  name: 'self-hosted'

steps:
- script: terraform --version
  displayName: 'Check Terraform version'

- script: az version
  displayName: 'Check Azure CLI'

- script: |
    terraform init
    terraform fmt -check
    terraform validate
  displayName: 'Terraform validation'